## pre-processamento
--> DSC_LOCALIDADE - BAIRROS

In [1]:
import pandas as pd
import folium
from setup_notebook import setup_path
setup_path()
from src.utils.functions import *
from folium.plugins import FastMarkerCluster
import webbrowser
import os
import time

In [2]:
#leitura do arquivo
#leitura do arquivo
arquivo_csv = '/home/akel/PycharmProjects/city_noise/data/raw/1501402_BELEM.csv'

# 2. Ler o arquivo CSV
df = pd.read_csv(arquivo_csv, sep=';', encoding='utf-8', low_memory=False)
df = df.rename(columns={'DSC_LOCALIDADE': 'Bairros'})
df['Bairros'] = df['Bairros'].str.replace('BELEM', 'INDEFINIDO')

In [3]:
df[df['Bairros'] == 'INDEFINIDO']

,COD_UNICO_ENDERECO,COD_UF,COD_MUNICIPIO,COD_DISTRITO,COD_SUBDISTRITO,COD_SETOR,NUM_QUADRA,NUM_FACE,CEP,Bairros,...,VAL_COMP_ELEM5,LATITUDE,LONGITUDE,NV_GEO_COORD,COD_ESPECIE,DSC_ESTABELECIMENTO,COD_INDICADOR_ESTAB_ENDERECO,COD_INDICADOR_CONST_ENDERECO,COD_INDICADOR_FINALIDADE_CONST,COD_TIPO_ESPECI
2218,181986367,15,1501402,150140255,15014025500,150140255000181P,2,5,66077115,INDEFINIDO,...,NaN,-1.457330,-48.456174,1,7,NaN,NaN,1.0,1.0,NaN
2219,4422125,15,1501402,150140255,15014025500,150140255000181P,2,5,66077115,INDEFINIDO,...,NaN,-1.457296,-48.456432,1,1,NaN,NaN,NaN,NaN,101.0
2220,4422127,15,1501402,150140255,15014025500,150140255000181P,2,5,66077115,INDEFINIDO,...,NaN,-1.457379,-48.456229,1,1,NaN,NaN,NaN,NaN,101.0
2221,4422129,15,1501402,150140255,15014025500,150140255000181P,2,5,66077115,INDEFINIDO,...,NaN,-1.457319,-48.456154,1,1,NaN,NaN,NaN,NaN,101.0
2222,108715260,15,1501402,150140255,15014025500,150140255000181P,2,5,66077115,INDEFINIDO,...,NaN,-1.457368,-48.456289,1,1,NaN,NaN,NaN,NaN,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613176,4573487,15,1501402,150140245,15014024500,150140245000008P,26,2,66640295,INDEFINIDO,...,NaN,-1.375331,-48.436909,1,1,NaN,NaN,NaN,NaN,101.0
613323,4573488,15,1501402,150140245,15014024500,150140245000008P,26,2,66640295,INDEFINIDO,...,NaN,-1.375231,-48.437027,1,1,NaN,NaN,NaN,NaN,101.0
613324,4573492,15,1501402,150140245,15014024500,150140245000008P,26,2,66640295,INDEFINIDO,...,NaN,-1.375786,-48.436646,1,1,NaN,NaN,NaN,NaN,101.0
613354,221106357,15,1501402,150140245,15014024500,150140245000008P,26,2,66640295,INDEFINIDO,...,NaN,-1.376228,-48.436267,3,1,NaN,NaN,NaN,NaN,101.0
613355,221106367,15,1501402,150140245,15014024500,150140245000008P,26,2,66640295,INDEFINIDO,...,NaN,-1.375711,-48.436660,1,1,NaN,NaN,NaN,NaN,101.0

In [4]:
import geopandas as gpd
from src.utils.update_bairros import atualizar_bairros




df = atualizar_bairros(df)

df[df['Bairros']=='INDEFINIDO']

7404 bairros indefinidos processados.
7404 bairros atualizados.
0 permaneceram sem bairro.

Empty DataFrame
Columns: [COD_UNICO_ENDERECO, COD_UF, COD_MUNICIPIO, COD_DISTRITO, COD_SUBDISTRITO, COD_SETOR, NUM_QUADRA, NUM_FACE, CEP, Bairros, NOM_TIPO_SEGLOGR, NOM_TITULO_SEGLOGR, NOM_SEGLOGR, NUM_ENDERECO, DSC_MODIFICADOR, NOM_COMP_ELEM1, VAL_COMP_ELEM1, NOM_COMP_ELEM2, VAL_COMP_ELEM2, NOM_COMP_ELEM3, VAL_COMP_ELEM3, NOM_COMP_ELEM4, VAL_COMP_ELEM4, NOM_COMP_ELEM5, VAL_COMP_ELEM5, LATITUDE, LONGITUDE, NV_GEO_COORD, COD_ESPECIE, DSC_ESTABELECIMENTO, COD_INDICADOR_ESTAB_ENDERECO, COD_INDICADOR_CONST_ENDERECO, COD_INDICADOR_FINALIDADE_CONST, COD_TIPO_ESPECI]
Index: []

[0 rows x 34 columns]